// src/components/InvoicePreview.jsx
import rightArrow from '../assets/icon-arrow-right.svg'
import Status from './Status'

export default function InvoicePreview({ id, due, amount, name, status, theme }) {
    return (
        <section id='invoice-preview' className={theme}>
            <h3><span>#</span>{id}</h3>
            <span>Due {due}</span>
            <p>{name}</p>
            <h2>£{amount}</h2>
            <Status
                status={status}
                theme={theme}
            />
            <img src={rightArrow} alt="right-arrow" />
        </section>
    )
}

// src/components/InvoicePreview.svelte
<script>
    import src from '/icon-arrow-right.svg'
    import {theme} from '../store'
    import Status from './Status.svelte';
    export let invoice

</script>

<a href={`#/invoice/${invoice.id}`} id="invoice-preview" class={$theme}>
    <h3><span>#</span>{invoice.id}</h3>
    <span>Due {invoice.paymentDue}</span>
    <p>{invoice.clientName}</p>
    <h2>£{invoice.total}</h2>
    <Status status={invoice.status} />
<img {src} alt="right-arrow" />
</a>
